title: "R&S Lab"
author: "Rahim Rasa"
description: "University of Mars"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true              # show site description and social links in the footer
show_excerpts: false           # show article excerpts on the home page
show_frame: true               # adds ar gray frame to the site
show_sidebar: false            #Show a sider instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/mars.pdf", title: "CV", icon: "home"}
  - {title: "Lab", url: "https://rs-lab.com}
  - {title: "Blog", file: "/blog.md"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons

  - {title: Mail, icon: envelope, url: "mailto:rasa@mars.com"}
  - {title: Github, icon: github, url: "https://github.com/marsrasa"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/gomyway1212"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
